// Loading Constants
export const START_POST_LOADING = "START_POST_LOADING";
export const END_POST_LOADING = "END_POST_LOADING";
export const START_PROFILE_LOADING = "START_PROFILE_LOADING";
export const END_PROFILE_LOADING = "END_PROFILE_LOADING";
export const START_PROFILE_FOLLOWING_LIST_LOADING =
  "START_PROFILE_FOLLOWING_LIST_LOADING";
export const END_PROFILE_FOLLOWING_LIST_LOADING =
  "END_PROFILE_FOLLOWING_LIST_LOADING";
export const START_PROFILE_FOLLOWERS_LIST_LOADING =
  "START_PROFILE_FOLLOWERS_LIST_LOADING";
export const END_PROFILE_FOLLOWERS_LIST_LOADING =
  "END_PROFILE_FOLLOWERS_LIST_LOADING";
export const START_FOllOW_UNFOLLOW_LOADING = "START_FOllOW_UNFOLLOW_LOADING";
export const END_FOllOW_UNFOLLOW_LOADING = " END_FOllOW_UNFOLLOW_LOADING";

// Auth CRUD Constants
export const AUTH = "AUTH";
export const LOGOUT = "LOGOUT";

// Post CRUD Constants
export const FETCH_ALL_POSTS = "FETCH_ALL_POSTS";
export const FETCH_POSTS_BY_FOLLOWING = "FETCH_POSTS_BY_FOLLOWING";
export const FETCH_BY_SEARCH = "FETCH_BY_SEARCH";
export const FETCH_POST_BY_ID = "FETCH_POST_BY_ID";
export const CREATE_POST = "CREATE_POST";
export const UPDATE_POST = "UPDATE_POST";
export const LIKE_POST = "LIKE_POST";
export const UNLIKE_POST = "UNLIKE_POST";
export const COMMENT_POST_WITH_USER_DETAILS = "COMMENT_POST_WITH_USER_DETAILS";
export const DELETE_POST = "DELETE_POST";
export const DELETE_USER_POST = "DELETE_USER_POST";
export const FETCH_POST_BY_USER = "FETCH_POST_BY_USER";
export const UPDATE_PROFILE_DETAILS = "UPDATE_PROFILE_DETAILS";
// export const UPDATE_PROFILE_PASSWORD = "UPDATE_PROFILE_PASSWORD";
export const UPDATE_PROFILE_PICTURES = "UPDATE_PROFILE_PICTURES";

// Profile CRUD Constants
export const GET_FOLLOWING_AND_FOLLOWERS_COUNT =
  "GET_FOLLOWING_AND_FOLLOWERS_COUNT";
export const GET_FOLLOWING_PROFILE_DETAILS = "GET_FOLLOWING_PROFILE_DETAILS";
export const GET_FOLLOWERS_PROFILE_DETAILS = "GET_FOLLOWERS_PROFILE_DETAILS";
export const GET_PROFILE_DETAILS = "GET_PROFILE_DETAILS";

// Request CRUD Constants
export const SEND_FOllOW_REQUEST = "SEND_FOllOW_REQUEST";
export const SEND_UNFOllOW_REQUEST = "SEND_UNFOllOW_REQUEST";
export const REMOVE_FOLLOWER = "REMOVE_FOLLOWER";
