export const FETCH_ALL_POSTS = "FETCH_ALL_POSTS";
export const FETCH_POSTS_BY_FOLLOWING = "FETCH_POSTS_BY_FOLLOWING";
export const FETCH_BY_SEARCH = "FETCH_BY_SEARCH";
export const FETCH_POST_BY_ID = "FETCH_POST_BY_ID";
export const CREATE_POST = "CREATE_POST";
export const UPDATE_POST = "UPDATE_POST";
export const LIKE_POST = "LIKE_POST";
export const UNLIKE_POST = "UNLIKE_POST";
export const COMMENT_POST_WITH_USER_DETAILS = "COMMENT_POST_WITH_USER_DETAILS";
export const DELETE_POST = "DELETE_POST";
export const DELETE_USER_POST = "DELETE_USER_POST";
export const FETCH_POST_BY_USER = "FETCH_POST_BY_USER";

export const GET_FOLLOWING_AND_FOLLOWERS_COUNT =
  "GET_FOLLOWING_AND_FOLLOWERS_COUNT";
export const GET_FOLLOWING_PROFILE_DETAILS = "GET_FOLLOWING_PROFILE_DETAILS";
export const GET_FOLLOWERS_PROFILE_DETAILS = "GET_FOLLOWERS_PROFILE_DETAILS";
export const GET_PROFILE_DETAILS = "GET_PROFILE_DETAILS";

export const START_LOADING = "START_LOADING";
export const END_LOADING = "END_LOADING";

export const AUTH = "AUTH";
export const LOGOUT = "LOGOUT";
